# <font color='blue'>Data Science Academy - Deep Learning Frameworks</font>

# Keras - Introdução

In [1]:
# Instalando keras
!pip install keras

In [2]:
import keras
print (keras.__version__)

Using TensorFlow backend.


2.0.4


## Carregando os Dados

Vamos criar um modelo de classificação de vinhos! Dataset utilizado:
    
http://mlr.cs.umass.edu/ml/datasets.html

In [3]:
!wget http://mlr.cs.umass.edu/ml/machine-learning-databases/wine/wine.data

--2017-05-05 21:11:02--  http://mlr.cs.umass.edu/ml/machine-learning-databases/wine/wine.data
Resolving mlr.cs.umass.edu (mlr.cs.umass.edu)... 128.119.246.96
Connecting to mlr.cs.umass.edu (mlr.cs.umass.edu)|128.119.246.96|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10782 (11K) [text/plain]
Saving to: ‘wine.data.2’

wine.data.2         100%[===================>]  10.53K  --.-KB/s    in 0.003s  

2017-05-05 21:11:02 (3.90 MB/s) - ‘wine.data.2’ saved [10782/10782]



In [4]:
# Importando pacotes fundamentais
import pandas
import numpy as np
from keras.utils import np_utils

In [5]:
# Como o dataset não possui header, vamos incluir
dados = pandas.read_csv("wine.data", names=["Class","Alcohol","Malic Alic","Ash","Alcanility of Ash","Magnesium",
                    "Total phenols","Flavanoids","Nonflavanoid phenols","Proanthocyanins","Color intensity","Hue","OD280_OD315_diluted wines",
                    "Proline"])

In [6]:
# Obtendo os valores de classe e armazenando em y
y = dados["Class"].values

In [7]:
print(y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]


In [8]:
# Ajustando o formato de y
# Converte array 1-D em matriz 
y_train = np_utils.to_categorical(y)

In [9]:
print(y_train)

[[ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  1.  0

In [10]:
# Keras espera receber as classes em diferentes colunas. Como temos 3 classes, precisamos de 3 colunas.
y_train = y_train[:,1:4]

In [11]:
print(y_train)

[[ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1. 

In [12]:
del(dados["Class"])
dados = dados.values

## Definindo a Arquitetura do Modelo

In [13]:
import keras

Em seguida, vamos importar o tipo de modelo Sequential do Keras. Isto é simplesmente uma pilha linear de camadas de rede neural, e é perfeito para o tipo de feed-forward CNN que estamos construindo.

In [14]:
from keras.models import Sequential

Em seguida, vamos importar as camadas "core" do Keras. Estas são as camadas que são usadas em quase qualquer rede neural.

In [15]:
from keras.layers import Dense, Dropout, Activation, Flatten

Agora importamos o otimizador, neste caso o SGD - Stochastic Gradient Descent

In [16]:
from keras.optimizers import SGD

Finalmente, vamos importar alguns utilitários. Isso nos ajudará a transformar nossos dados.

In [17]:
from keras.utils import np_utils

## Construindo as Camadas

In [18]:
model = Sequential()

Camadas totalmente conectadas são definidas usando a classe Dense. Podemos especificar o número de neurônios na camada como o primeiro argumento, o método de inicialização como o segundo argumento com kernel_initializer e especificar a função de ativação usando o argumento activation.

O valor 'normal' no parâmetro kernel_initializer gera pequenos valores randômicos com uma distirbuição Graussiana (normal).

Usaremos a função de ativação ReLu nas duas primeiras camadas e a função sigmóide na camada de saída. Costumava-se usar as funções da ativação sigmoid e tanh para todas as camadas. Mas atualmente, o melhor desempenho é alcançado usando a função de ativação ReLu. Usamos um sigmoide nas camadas internas para garantir que nossa saída de rede esteja entre 0 e 1 e e função softmax na camada de saída, comumente usada em problemas de classificação.

In [19]:
model.add(Dense(40, input_dim = 13, kernel_initializer = 'normal', activation = 'relu'))

In [20]:
model.add(Dense(10, kernel_initializer = 'normal', activation = "sigmoid"))

In [21]:
model.add(Dropout(0.10))

In [22]:
model.add(Dense(5, kernel_initializer = 'normal', activation = "sigmoid"))

In [23]:
model.add(Dense(3, kernel_initializer = 'normal', activation = "softmax"))

## Otimização com Stochastic Gradient Descent

Mais otimizadores em: https://keras.io/optimizers/

In [24]:
sgd = keras.optimizers.Adam(lr = 0.001, beta_1 = 0.9, beta_2 = 0.999, epsilon = 1e-08, decay = 0.0)

## Compilação do Modelo e Treinamento

In [25]:
model.compile(loss = 'categorical_crossentropy', optimizer = sgd,  metrics = ["acc"])

In [26]:
model.fit(dados, y_train, epochs = 1600, verbose = 1)

Epoch 1/1600
178/178 [==============================] - 0s - loss: 1.0943 - acc: 0.3989     
Epoch 2/1600
178/178 [==============================] - 0s - loss: 1.0929 - acc: 0.3989     
Epoch 3/1600
178/178 [==============================] - 0s - loss: 1.0914 - acc: 0.3989     
Epoch 4/1600
178/178 [==============================] - 0s - loss: 1.0907 - acc: 0.3989     
Epoch 5/1600
178/178 [==============================] - 0s - loss: 1.0895 - acc: 0.3989     
Epoch 6/1600
178/178 [==============================] - 0s - loss: 1.0885 - acc: 0.3989     

In [27]:
score = model.evaluate(dados, y_train, verbose = 0)

In [28]:
print(score)

[0.068357668356614165, 0.9831460674157303]


## Fim